### ISSUE TITLE
Are there any plans to open source Sermoon V1  3d printer?

### ISSUE THREAD

**Issue by duchengyao** [CrealityOfficial/sermoon-d1#3]
BTW: what's the marlin version of  Sermoon V1 `SermoonV1Pro-HW-V200-SW-V3.0.35-SC-V3.0.12 13 Apr. 2022`

**Comment by CrealityTech** [comment]
we have pulished Sermoon-v1/v1pro source code https://github.com/CrealityOfficial/Sermoon-V1
